- name: Install HTTPD and Configure Website
  hosts: all
  tasks:

    - name: Install HTTPD
      command: yum install -y httpd

    - name: Stop service HTTPD
      service:
        name: httpd
        state: stopped

    - name: Enable service HTTPD
      service:
        name: httpd
        enabled: yes

    - name: Create Website Page
      copy:
        dest: "/etc/httpd/html/index.html"
        content: Hello {{ NAME }}

    - name: Start service HTTPD
      service:
        name: httpd
        state: started
    - name: Stop service IpTables
      service:
        name: iptables
        state: stopped

